<?php
/**
 * PHPMaker 2021 user level settings
 */
namespace PHPMaker2021\inplaze;

// User level info
$USER_LEVELS = [["-2","Anonymous"],
    ["0","Default"]];
// User level priv info
$USER_LEVEL_PRIVS = [["{inplaze}.htaccess","-2","0"],
    ["{inplaze}.htaccess","0","0"],
    ["{inplaze}blog","-2","0"],
    ["{inplaze}blog","0","0"],
    ["{inplaze}category","-2","0"],
    ["{inplaze}category","0","0"],
    ["{inplaze}contents","-2","0"],
    ["{inplaze}contents","0","0"],
    ["{inplaze}course.php","-2","0"],
    ["{inplaze}course.php","0","0"],
    ["{inplaze}icon","-2","0"],
    ["{inplaze}icon","0","0"],
    ["{inplaze}icon_list","-2","0"],
    ["{inplaze}icon_list","0","0"],
    ["{inplaze}image","-2","0"],
    ["{inplaze}image","0","0"],
    ["{inplaze}inc_final.php","-2","0"],
    ["{inplaze}inc_final.php","0","0"],
    ["{inplaze}inc_init.php","-2","0"],
    ["{inplaze}inc_init.php","0","0"],
    ["{inplaze}inc_js.js","-2","0"],
    ["{inplaze}inc_js.js","0","0"],
    ["{inplaze}product","-2","0"],
    ["{inplaze}product","0","0"],
    ["{inplaze}real-estate.php","-2","0"],
    ["{inplaze}real-estate.php","0","0"],
    ["{inplaze}tag","-2","0"],
    ["{inplaze}tag","0","0"],
    ["{inplaze}text","-2","0"],
    ["{inplaze}text","0","0"],
    ["{inplaze}user","-2","0"],
    ["{inplaze}user","0","0"],
    ["{inplaze}user_level","-2","0"],
    ["{inplaze}user_level","0","0"],
    ["{inplaze}user_level_permission","-2","0"],
    ["{inplaze}user_level_permission","0","0"],
    ["{inplaze}detox.php","-2","0"],
    ["{inplaze}detox.php","0","0"]];
// User level table info
$USER_LEVEL_TABLES = [[".htaccess","htaccess",".htaccess",false,"{inplaze}","Htaccess"],
    ["blog","blog","Blog",true,"{inplaze}","BlogList"],
    ["category","category","Category",true,"{inplaze}","CategoryList"],
    ["contents","contents","Content",true,"{inplaze}","ContentsList"],
    ["course.php","course","course.php",false,"{inplaze}","Course"],
    ["icon","icon","Icon",true,"{inplaze}",""],
    ["icon_list","icon_list","Icon Library",true,"{inplaze}",""],
    ["image","image","Image",true,"{inplaze}","ImageList"],
    ["inc_final.php","inc_final","inc_final.php",false,"{inplaze}","IncFinal"],
    ["inc_init.php","inc_init","inc_init.php",false,"{inplaze}","IncInit"],
    ["inc_js.js","inc_jsjs","inc_js.js",false,"{inplaze}","IncJsJs"],
    ["product","product","Product",true,"{inplaze}","ProductList"],
    ["real-estate.php","realestate","real-estate.php",false,"{inplaze}","RealEstate"],
    ["tag","tag","Tag",true,"{inplaze}","TagList"],
    ["text","text","Text",true,"{inplaze}","TextList"],
    ["user","user","User",true,"{inplaze}","UserList"],
    ["user_level","user_level2","Level",true,"{inplaze}","UserLevel2List"],
    ["user_level_permission","user_level_permission","Permission",true,"{inplaze}",""],
    ["detox.php","detox","detox.php",false,"{inplaze}","Detox"]];
